config/routes.rb
Easymse2::Application.routes.draw do
  
  resources :clients do
    resources :entries
  end

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :user
  attr_accessible :date_of_birth, :first_name, :identifier, :last_name, :notes, :primary_phone
  
  has_many :entries
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  # GET /clients
  # GET /clients.json
  
  def index
    @clients = current_user.clients.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clients }
    end
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @client = current_user.clients.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/new
  # GET /clients/new.json
  def new
    @client = current_user.clients.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/1/edit
  def edit
    @client = current_user.clients.find(params[:id])
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = current_user.clients.new(params[:client])

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'You have successfully added a client' }
        format.json { render json: @client, status: :created, location: @client }
      else
        format.html { render action: "new" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clients/1
  # PUT /clients/1.json
  def update
    @client = current_user.clients.find(params[:id])

    respond_to do |format|
      if @client.update_attributes(params[:client])
        format.html { redirect_to @client, notice: 'Client information was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client = current_user.clients.find(params[:id])
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'The client has been permanently deleted.' }
      format.json { head :no_content }
    end
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= simple_form_for(@client, :html => { :class => "form-horizontal" }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :identifier %>
    <%= f.input :date_of_birth %>
    <%= f.input :primary_phone %>
    <%= f.input :notes %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing <%= @client.identifier %>'s Information</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<h1>Your Clients</h1>
<table>
  <thead>
	  <tr>
  		<th>Private ID</th>
  		<th>Name</th>
  		<th>Notes</th>
  		<th>Entries</th>
  		<th><%= render "shared/private-toggle" %></th>
		</tr>
	</thead>
  <% if @clients.count > 0 %>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.identifier %></td>
        <td class="private-data"><span><%= client.first_name %> <%= client.last_name %></span></td>
        <td class="private-data"><span><%= client.notes %></span></td>
        <td>
          <%= link_to client_entries_path(client) do %><%= client.entries.count %> entries<% end %> | 
          <%= link_to 'New Entry', new_client_entry_path(client, @entry) %> | 
          <%= link_to 'View Details', client %>
          <%# link_to 'Edit', edit_client_path(client) %><%# link_to 'Destroy', client, method: :delete, data: { confirm: 'Deleting this client is permanent. You will subsequently lose any information related to this client (including entries) should you continue.  Are you still sure you want to delete this client?' } %></td>
      </tr>
      <tr>
        <td colspan="9" class="text-center"><%= link_to 'Add a New Client', new_client_path %></td>
      </tr>
    <% end %>
  <% else %>
    <tr>
      <td colspan="9">You have not yet added any clients. <%= link_to 'Click here to add a client', new_client_path %></td>
    </tr>
  <% end %>
</table>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>


<%= render "shared/private-toggle" %>
<p>
  <b>First name:</b>
  <span class="private-data"><span><%= @client.first_name %></span></span>
</p>

<p>
  <b>Last name:</b>
  <span class="private-data"><span><%= @client.last_name %></span></span>
</p>

<p>
  <b>Identifier:</b>
  <%= @client.identifier %>
</p>

<p>
  <b>Date of birth:</b>
  <%= @client.date_of_birth %>
</p>

<p>
  <b>Primary phone:</b>
  <span class="private-data"><span><%= @client.primary_phone %></span></span>
</p>

<p>
  <b>Notes:</b>
  <%= @client.notes %>
</p>


<%= link_to 'Edit Client Information', edit_client_path(@client) %>